verbose-logging: false
messages:
  not-sent: '<color:#bc7457>Your message was not sent!'
  command:
    prefix: '<color:#bc7457>[ChatRestrict]</color><color:#306f88>:</color> '
    no-permission: '<red>No permission!'
    chat-restrict:
      usage: '<color:#bc7457>Incorrect format! <color:#306f88>Use /chatrestrict <reload | enable/disable> [rule]</color:#306f88>'
      reload: '<color:gray>Reloaded in <color:#306f88><ms></color:#306f88> milliseconds.'
      toggle-rule-not-found: '<color:#bc7457>Rule was not found!'
      toggle-rule: '<color:gray><color:#306f88><rulename></color:#306f88> is now <color:#306f88><status></color:#306f88>.'
      muteall-enabled: '<color:gray>Players no longer have the ability to chat.'
      muteall-disabled: '<color:gray>Players now have the ability to chat. Rules are followed.'
      allrules-enabled: '<color:gray>All rules have been enabled.'
      allrules-disabled: '<color:gray>All rules have been disabled.'
